name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    #- name: configure
    #  run: ./configure
    - name: ./src/compil.sh
      run: ./src/compil.sh
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
